// <auto-generated />
using System.Collections.Generic;
using DigitalDevices.ProductTypesService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalDevices.ProductTypesService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductTypesContext))]
    partial class ProductTypesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalDevices.ProductTypesService.Core.Models.ProductTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<int>>("CharacteristicsTypesIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("CharacteristicsTypesIds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.PrimitiveCollection<List<int>>("ProductsIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ProductsIds");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
