// <auto-generated />
using System;
using DigitalDevices.CharacteristicsService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalDevices.CharacteristicsService.Infrastructure.Migrations
{
    [DbContext(typeof(CharacteristicsContext))]
    [Migration("20250725074313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalDevices.CharacteristicsService.Core.Models.Characteristics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacteristicsTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicsTypeId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("DigitalDevices.CharacteristicsService.Core.Models.CharacteristicsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DataType");

                    b.Property<string>("EnumType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EnumType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("CharacteristicsType");
                });

            modelBuilder.Entity("DigitalDevices.CharacteristicsService.Core.Models.CharacteristicsTypeProductTypes", b =>
                {
                    b.Property<Guid>("ProductTypesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacteristicsTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductTypesId", "CharacteristicsTypeId");

                    b.ToTable("CharacteristicsTypeProductTypes");
                });

            modelBuilder.Entity("DigitalDevices.CharacteristicsService.Core.Models.Characteristics", b =>
                {
                    b.HasOne("DigitalDevices.CharacteristicsService.Core.Models.CharacteristicsType", "CharacteristicsType")
                        .WithMany("Characteristics")
                        .HasForeignKey("CharacteristicsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicsType");
                });

            modelBuilder.Entity("DigitalDevices.CharacteristicsService.Core.Models.CharacteristicsType", b =>
                {
                    b.Navigation("Characteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
